#!/bin/sh

# Redirect all incoming tcp traffic to port 9040
iptables -t nat -A PREROUTING -i vif+ -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j REDIRECT --to-ports 9040
# Discard udp traffic except DNS (which is intercepted by Qubes anyway)
#iptables -t nat -A PREROUTING -i vif+ -p udp -m udp --dport 53 -j ACCEPT
#iptables -t nat -A PREROUTING -i vif+ -j DROP

# Protect from mailformed packets similar to tor leaks protection
# Allow packets to tcp port 9040
# Note we are using -I instead of -A
iptables -I INPUT -i vif+ -p tcp -m tcp --dport 9040 -j ACCEPT
iptables -I INPUT -m state --state INVALID -j DROP
iptables -I INPUT -m conntrack --ctstate INVALID -j DROP
iptables -I INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG FIN,SYN,RST,ACK -j DROP
iptables -I INPUT -p tcp -m tcp --tcp-flags FIN,SYN FIN,SYN -j DROP
iptables -I INPUT -p tcp -m tcp --tcp-flags SYN,RST SYN,RST -j DROP
iptables -I INPUT -f -j DROP
iptables -I INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG FIN,SYN,RST,PSH,ACK,URG -j DROP
iptables -I INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG NONE -j DROP
iptables -I INPUT -p icmp -j DROP
