listen_addresses = ['127.0.0.1:9053']
server_names = ['cloudflare', 'digitale-ch', 'nextdns', 'mullvad-doh', 'quad9-doh-ip4-port443-nofilter-pri-1']
force_tcp = true
proxy = 'socks5://127.0.0.1:1080'
fallback_resolvers = ['9.9.9.9:53', '8.8.8.8:53', '1.1.1.1:53']

block_ipv6 = true
cache = true

### Only needed to configure static nodes
#ipv4_servers = true
#ipv6_servers = false
#dnscrypt_servers = false
#doh_servers = true
#odoh_servers = false
#require_dnssec = false
#require_nolog = true
#require_nofilter = true
#[sources]
#  [sources.'public-resolvers']
#  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
#  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
#  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#  refresh_delay = 72
#  prefix = ''

[static]

  [static.'cloudflare']
  stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjEAEmRucy5jbG91ZGZsYXJlLmNvbQovZG5zLXF1ZXJ5'

  [static.'digitale-ch']
  stamp = 'sdns://AgcAAAAAAAAADTE4NS45NS4yMTguNDKgzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984cZG5zLmRpZ2l0YWxlLWdlc2VsbHNjaGFmdC5jaAovZG5zLXF1ZXJ5'

  [static.'nextdns']
  stamp = 'sdns://AgcAAAAAAAAACjQ1LjkwLjMwLjAgmjo09yfeubylEAPZzpw5-PJ92cUkKQHCurGkTmNaAhkWYW55Y2FzdC5kbnMubmV4dGRucy5pbwovZG5zLXF1ZXJ5'

  [static.'mullvad-doh']
  stamp = 'sdns://AgcAAAAAAAAAACD5_zfwLmMstzhwJcB-V5CKPTcbfJXYzdA5DeIx7ZQ6Eg9kb2gubXVsbHZhZC5uZXQKL2Rucy1xdWVyeQ'

  [static.'quad9-doh-ip4-port443-nofilter-pri-1']
  stamp = 'sdns://AgYAAAAAAAAACDkuOS45LjEwICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKFGRuczEwLnF1YWQ5Lm5ldDo1MDUzCi9kbnMtcXVlcnk'
