#!/bin/bash

AUDIOVM="$(xenstore-read name)"
while IFS= read -rd $'\0' EVENT_WORD ; do
    if [ -z ${EVENT_WORD} ] ; then
        CHECK_VM=""
        case "${EVENT_LINE}" in
            connection-established*)
                while read -r VM_LINE ; do
                    VM_LINE="${VM_LINE#0}"
                    IFS=' ' set -- "junk" ${VM_LINE}
                    [ x"${3}" != x"class=AdminVM" ] && [ x"${4}" = x"state=Running" ] && CHECK_VM="${2}"
                done < <(echo -n '' | qrexec-client-vm dom0 admin.vm.List) ;;
            *domain-start*)
                IFS=' ' set -- "junk" ${EVENT_LINE}
                [ x"${4}" = x"domain-start" ] && CHECK_VM="${3}" ;;
        esac
        EVENT_LINE=""
        if ! [ -z ${CHECK_VM} ] ; then
            while read -r CHECK_LINE ; do
                IFS=' ' set -- "junk" ${CHECK_LINE}
                case "${2}" in
                    audiovm) CHECK_AUDIOVM="${5}" ;;
                    xid) CHECK_XID="${5}" ;;
                esac
            done < <(echo -n '' | qrexec-client-vm "${CHECK_VM}" admin.vm.property.GetAll)
            [ x"${CHECK_AUDIOVM}" = x"${AUDIOVM}" ] && /usr/bin/pacat-simple-vchan "${CHECK_XID}" "${CHECK_VM}" &
        fi
    else
        [ -z "${EVENT_LINE}" ] && EVENT_LINE="${EVENT_WORD}" || EVENT_LINE="${EVENT_LINE} ${EVENT_WORD}"
    fi
done < <(echo -n '' | qrexec-client-vm dom0 admin.Events)
